openapi: 3.0.0
info:
  description: This API is used for sending whatsapp via API
  title: TTE Service
  version: 1.0.0
servers:
- url: http://localhost:10020
tags:
- description: Esign module
  name: esign
paths:
  /api/esign/nik/{nik}:
    get:
      description: Get user information
      parameters:
      - description: "NIK, Nomor Induk Kepegawaian"
        explode: false
        in: path
        name: nik
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_api_esign_nik__nik__get_200_response'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Get user information
      tags:
      - esign
  /api/esign/sign:
    post:
      description: Add signature to a document
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/_api_esign_sign_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignResponse'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Add signature to a document
      tags:
      - esign
  /api/esign/verify/id:
    get:
      description: Can be reference code/esign id
      parameters:
      - description: Esign ID / Reference Code
        explode: true
        in: query
        name: id
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EsignResult'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Verify signature
      tags:
      - esign
  /api/esign/verify/doc:
    post:
      description: Can be reference code or esign id
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/_api_esign_verify_doc_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EsignDetails'
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Verify signature
      tags:
      - esign
components:
  schemas:
    SignResponse:
      example:
        message: Tanda tangan berhasil
        results:
          layanan: SIL
          file_name: booking-form.pdf
          ref_code: 41ed6661-a5b8-4de2-8d3d-9431ba57f331
          file_link: https://dev-esign.storage.bbkkp.kemenperin.go.id/esign/1d77d74c22914956a19342a56d0e48aa.pdf?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=PtQGQ0HGzoigu750B50G%2F20240723%2Fs3%2Fs3%2Faws4_request&X-Amz-Date=20240723T060356Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=a6576960b6dfcc728c4c069303fe55e21071e8264ee84c023c0efec071d3cfce
          id: 9c96caee-6b7e-491c-bbab-30c3da0442a9
      properties:
        message:
          example: Tanda tangan berhasil
          type: string
        results:
          $ref: '#/components/schemas/SignResponse_results'
      type: object
    EsignDetails:
      example:
        summary: VALID
        jumlah_signature: 1
        notes: "Dokumen valid, Sertifikat yang digunakan terpercaya"
        nama_dokumen: booking-form.pdf
        details:
        - info_tsa:
            name: Timestamp Authority Badan Siber dan Sandi Negara
            tsa_cert_validity: tsa_cert_validity
          signature_field: sig_1721714634534
          info_signer:
            issuer_dn: "C=ID,O=Lembaga Sandi Negara,CN=OSD LU Kelas 2"
            signer_name: Hantek Production
            signer_cert_validity: 2024-07-23 13:03:59.603 to 2024-07-23 13:03:59.603
            signer_dn: Hantek Production
            cert_user_certified: true
          signature_document:
            signed_using_tsa: true
            reason: reason
            document_integrity: true
            signature_value: signature_value
            signed_in: 2024-07-23 13:03:59.603
            location: location
            hash_value: hash_value
        - info_tsa:
            name: Timestamp Authority Badan Siber dan Sandi Negara
            tsa_cert_validity: tsa_cert_validity
          signature_field: sig_1721714634534
          info_signer:
            issuer_dn: "C=ID,O=Lembaga Sandi Negara,CN=OSD LU Kelas 2"
            signer_name: Hantek Production
            signer_cert_validity: 2024-07-23 13:03:59.603 to 2024-07-23 13:03:59.603
            signer_dn: Hantek Production
            cert_user_certified: true
          signature_document:
            signed_using_tsa: true
            reason: reason
            document_integrity: true
            signature_value: signature_value
            signed_in: 2024-07-23 13:03:59.603
            location: location
            hash_value: hash_value
      properties:
        nama_dokumen:
          example: booking-form.pdf
          type: string
        jumlah_signature:
          example: 1
          type: integer
        notes:
          example: "Dokumen valid, Sertifikat yang digunakan terpercaya"
          type: string
        details:
          items:
            $ref: '#/components/schemas/SignatureDetail'
          type: array
        summary:
          example: VALID
          type: string
      type: object
    SignatureDetail:
      example:
        info_tsa:
          name: Timestamp Authority Badan Siber dan Sandi Negara
          tsa_cert_validity: tsa_cert_validity
        signature_field: sig_1721714634534
        info_signer:
          issuer_dn: "C=ID,O=Lembaga Sandi Negara,CN=OSD LU Kelas 2"
          signer_name: Hantek Production
          signer_cert_validity: 2024-07-23 13:03:59.603 to 2024-07-23 13:03:59.603
          signer_dn: Hantek Production
          cert_user_certified: true
        signature_document:
          signed_using_tsa: true
          reason: reason
          document_integrity: true
          signature_value: signature_value
          signed_in: 2024-07-23 13:03:59.603
          location: location
          hash_value: hash_value
      properties:
        info_tsa:
          $ref: '#/components/schemas/InfoTSA'
        signature_field:
          example: sig_1721714634534
          type: string
        info_signer:
          $ref: '#/components/schemas/InfoSigner'
        signature_document:
          $ref: '#/components/schemas/SignatureDocument'
      type: object
    InfoTSA:
      example:
        name: Timestamp Authority Badan Siber dan Sandi Negara
        tsa_cert_validity: tsa_cert_validity
      properties:
        name:
          example: Timestamp Authority Badan Siber dan Sandi Negara
          type: string
        tsa_cert_validity:
          nullable: true
          type: string
          example: null
      type: object
    InfoSigner:
      example:
        issuer_dn: "C=ID,O=Lembaga Sandi Negara,CN=OSD LU Kelas 2"
        signer_name: Hantek Production
        signer_cert_validity: 2024-07-23 13:03:59.603 to 2024-07-23 13:03:59.603
        signer_dn: Hantek Production
        cert_user_certified: true
      properties:
        issuer_dn:
          example: "C=ID,O=Lembaga Sandi Negara,CN=OSD LU Kelas 2"
          type: string
        signer_name:
          example: Hantek Production
          type: string
        signer_cert_validity:
          example: 2024-07-23 13:03:59.603 to 2024-07-23 13:03:59.603
          type: string
        signer_dn:
          example: Hantek Production
          type: string
        cert_user_certified:
          example: true
          type: boolean
      type: object
    SignatureDocument:
      example:
        signed_using_tsa: true
        reason: reason
        document_integrity: true
        signature_value: signature_value
        signed_in: 2024-07-23 13:03:59.603
        location: location
        hash_value: hash_value
      properties:
        signed_using_tsa:
          example: true
          type: boolean
        reason:
          nullable: true
          type: string
          example: null
        document_integrity:
          example: true
          type: boolean
        signature_value:
          nullable: true
          type: string
          example: null
        signed_in:
          example: 2024-07-23 13:03:59.603
          type: string
        location:
          nullable: true
          type: string
          example: null
        hash_value:
          nullable: true
          type: string
          example: null
      type: object
    EsignResult:
      example:
        layanan: SIL
        file_name: booking-form.pdf
        ref_code: 87e685ab-3a6f-414f-9d46-9b1515b756d6
        file_link: https://dev-esign.storage.bbkkp.kemenperin.go.id/esign/1d77d74c22914956a19342a56d0e48aa.pdf?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=PtQGQ0HGzoigu750B50G%2F20240723%2Fs3%2Fs3%2Faws4_request&X-Amz-Date=20240723T061352Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=d3b902cb59fe8405109c8e0b2318b6abc0b5c8c6bec133ef5f39a02e84a2498b
        id: 9c96caee-6b7e-491c-bbab-30c3da0442a9
        message: Data TTE ditemukan
        esign_details:
          summary: VALID
          jumlah_signature: 1
          notes: "Dokumen valid, Sertifikat yang digunakan terpercaya"
          nama_dokumen: booking-form.pdf
          details:
          - info_tsa:
              name: Timestamp Authority Badan Siber dan Sandi Negara
              tsa_cert_validity: tsa_cert_validity
            signature_field: sig_1721714634534
            info_signer:
              issuer_dn: "C=ID,O=Lembaga Sandi Negara,CN=OSD LU Kelas 2"
              signer_name: Hantek Production
              signer_cert_validity: 2024-07-23 13:03:59.603 to 2024-07-23 13:03:59.603
              signer_dn: Hantek Production
              cert_user_certified: true
            signature_document:
              signed_using_tsa: true
              reason: reason
              document_integrity: true
              signature_value: signature_value
              signed_in: 2024-07-23 13:03:59.603
              location: location
              hash_value: hash_value
          - info_tsa:
              name: Timestamp Authority Badan Siber dan Sandi Negara
              tsa_cert_validity: tsa_cert_validity
            signature_field: sig_1721714634534
            info_signer:
              issuer_dn: "C=ID,O=Lembaga Sandi Negara,CN=OSD LU Kelas 2"
              signer_name: Hantek Production
              signer_cert_validity: 2024-07-23 13:03:59.603 to 2024-07-23 13:03:59.603
              signer_dn: Hantek Production
              cert_user_certified: true
            signature_document:
              signed_using_tsa: true
              reason: reason
              document_integrity: true
              signature_value: signature_value
              signed_in: 2024-07-23 13:03:59.603
              location: location
              hash_value: hash_value
      properties:
        id:
          example: 9c96caee-6b7e-491c-bbab-30c3da0442a9
          type: string
        layanan:
          example: SIL
          type: string
        ref_code:
          example: 87e685ab-3a6f-414f-9d46-9b1515b756d6
          type: string
        file_name:
          example: booking-form.pdf
          type: string
        file_link:
          example: https://dev-esign.storage.bbkkp.kemenperin.go.id/esign/1d77d74c22914956a19342a56d0e48aa.pdf?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=PtQGQ0HGzoigu750B50G%2F20240723%2Fs3%2Fs3%2Faws4_request&X-Amz-Date=20240723T061352Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=d3b902cb59fe8405109c8e0b2318b6abc0b5c8c6bec133ef5f39a02e84a2498b
          type: string
        esign_details:
          $ref: '#/components/schemas/EsignDetails'
        message:
          example: Data TTE ditemukan
          type: string
      type: object
    _api_esign_nik__nik__get_200_response:
      example:
        message: User dengan nik 0803202100007XXX ISSUE
        results: true
      properties:
        results:
          type: boolean
        message:
          example: User dengan nik 0803202100007XXX ISSUE
          type: string
      type: object
    _api_esign_sign_post_request:
      properties:
        file:
          format: binary
          type: string
        nik:
          type: string
        passphrase:
          example: yourSecretPassphrase
          type: string
        ref_code:
          description: Reference code adalah nomor unik disetiap layanan untuk verifikasi
            dokumen
          example: 41ed6661-a5b8-4de2-8d3d-9431ba57f331
          type: string
      type: object
    _api_esign_verify_doc_post_request:
      properties:
        signed_file:
          format: binary
          type: string
      type: object
    SignResponse_results:
      example:
        layanan: SIL
        file_name: booking-form.pdf
        ref_code: 41ed6661-a5b8-4de2-8d3d-9431ba57f331
        file_link: https://dev-esign.storage.bbkkp.kemenperin.go.id/esign/1d77d74c22914956a19342a56d0e48aa.pdf?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=PtQGQ0HGzoigu750B50G%2F20240723%2Fs3%2Fs3%2Faws4_request&X-Amz-Date=20240723T060356Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=a6576960b6dfcc728c4c069303fe55e21071e8264ee84c023c0efec071d3cfce
        id: 9c96caee-6b7e-491c-bbab-30c3da0442a9
      properties:
        id:
          example: 9c96caee-6b7e-491c-bbab-30c3da0442a9
          type: string
        layanan:
          example: SIL
          type: string
        ref_code:
          example: 41ed6661-a5b8-4de2-8d3d-9431ba57f331
          type: string
        file_name:
          example: booking-form.pdf
          type: string
        file_link:
          example: https://dev-esign.storage.bbkkp.kemenperin.go.id/esign/1d77d74c22914956a19342a56d0e48aa.pdf?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=PtQGQ0HGzoigu750B50G%2F20240723%2Fs3%2Fs3%2Faws4_request&X-Amz-Date=20240723T060356Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=a6576960b6dfcc728c4c069303fe55e21071e8264ee84c023c0efec071d3cfce
          type: string
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
